name: NPM publish library
on: [push]

jobs:
  build:
    environment:
      name: build
    name: Publish to npm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        name: Checking out code
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_API_KEY }}
      - run: npm run build
        env:
          NPM_TOKEN: ${{ secrets.NPM_API_KEY }}

  publish:
    environment:
      name: challonge-js-sdk
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checking out code
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Print variables
        run: |
          printenv
      - name: Publish
        run: |
          npm publish --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_API_KEY }}
